### PR TITLE
Merging Palkeo's changes

### LINKED ISSUE #93: Önemli

### LINKED ISSUE #98: AIT
0x20Cf18E81Cb2921BE7e5B1F00835Ba3aa7B8F0Fd

### PR DESCRIPTION
**Pull request by kolinko**

### CODE REVIEW

**Review by Kamranwew70 — APPROVED** [review]

**Comment by Carsonmarvel1** [comment]
Pleased give me back my coins

**Review by axljoker03 — APPROVED** [review]
ok

**Review by axljoker03 — COMMENTED** [review]
#13

**Review by axljoker03 — APPROVED** [review]

**Comment by jackromo888** [comment]
U

**Review by jackromo888 — APPROVED** [review]
Thanks

**Review by axljoker03 — APPROVED** [review]

**Review by Qmig — COMMENTED** [review]
And then you

**Review by Herand19 — COMMENTED** [review]
Hya

**Review by hhjmmmmmmmm — APPROVED** [review]

**Review by hhjmmmmmmmm — APPROVED** [review]

**Review by hhjmmmmmmmm — APPROVED** [review]

**Review by hhjmmmmmmmm — APPROVED** [review]

**Comment by tawhidnazari57** [comment]
0x283d7b3750b7000a1c8412363da09291f5b7d017

**Review by tawhidnazari57 — COMMENTED** [review]
0x283d7b3750b7000a1c8412363da09291f5b7d017

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by Shakacro — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by MrG9090 — APPROVED** [review]

**Review by bellCChi — COMMENTED** [review]
☺️

**Review by Fool256 — APPROVED** [review]

**Review by bellCChi — COMMENTED** [review]
Wonderful and thank you this is still so hard to get but I really appreciate the help its absolutely amazing thanks so much

**Comment by rangel0828** [comment]
😉

**Review by rangel0828 — COMMENTED** [review]
Goooo

**Review by fdtwd8vv45-sketch — COMMENTED** [review]
Try

**Review by ghost — APPROVED** [review]

**Comment by armandRobled** [comment]
8516669c06409dd4cc4be62347ba6d934c4d44b5

**Review by Dustin4444 — COMMENTED** [review]
Fixes #273

**Comment by hzaa515** [comment]
[]()

**Review by Revengeserved — COMMENTED** [review]
Tanks

**Review by Revengeserved — COMMENTED** [review]
Tanks

**Review by 76alexisrodri — COMMENTED** [review]
De

**Comment by wyattloveslife-create** [comment]
Hey so why delete all my positions?

**Comment by repaarafath945-cyber** [comment]
Delete what ?

**Pull request merged**
